defaults:
  - _self_
  - env: robosuite

name: lift_image
env_name: Lift
obs_keys:
- agentview_image
- robot0_eye_in_hand_image
- robot0_eef_pos
- robot0_eef_quat
- robot0_gripper_qpos
max_episode_steps: 200
num_episodes: 50