defaults:
  - _self_
  - env: robosuite_3d

name: lift_pc
env_name: Lift
obs_keys:
- frontview_pc
- robot0_eye_in_hand_pc
- robot0_eef_pos
- robot0_eef_quat
- robot0_gripper_qpos
num_points: 512
bounding_boxes:
  frontview:
    x: [-0.5, 0.5]
    y: [-0.4, 2]
    z: [1, 2.35]
  robot0_eye_in_hand:
    x: [-0.5, 0.5]
    y: [-0.5, 0.5]
    z: [0, 0.5]
max_episode_steps: 200
num_episodes: 2