_target_: sim_demo_collector.env.robosuite.RobosuiteEnv
env_name: ${task.name}
robots: Panda
camera_names:
  - agentview
  - robot0_eye_in_hand
obs_modalities:
  - low_dims
  - rgb
  - depth
  - point_cloud
  - rgb_mask
  - pcd_mask
image_size: [84, 84]
num_points: ${task.num_points}
bounding_boxes: ${task.bounding_boxes}
controller: OSC_POSE
delta_action: true
control_freq: 20
render_mode: rgb_array
render_camera: agentview
