_target_: sim_demo_collector.env.robosuite.RobosuiteEnv3D
env_name: ${task.name}
robots: Panda
use_object_obs: false
use_image_obs: true
use_depth_obs: true
use_mask_obs: true
image_size: [84, 84]
num_points: ${task.num_points}
bounding_boxes: ${task.bounding_boxes}
controller: OSC_POSE
delta_action: true
control_freq: 20
render_mode: rgb_array
render_camera: agentview