_target_: sim_demo_collector.env.robosuite.RobosuiteEnv3D
env_name: ${task.env_name}
robots: Panda
camera_names:
- agentview
- frontview
- robot0_eye_in_hand
use_object_obs: false
use_image_obs: true
use_depth_obs: false
use_pc_obs: true
use_mask_obs: true
flatten_obs: false
image_size: [84, 84]
num_points: ${task.num_points}
bounding_boxes: ${task.bounding_boxes}
normalize_pc: true
controller: OSC_POSE
delta_action: false
control_freq: 20
render_mode: rgb_array
render_camera: agentview
render_image_size: [256, 256]